//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp3_Azure.Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/Tp3_Azure.Domain")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProdutoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantidadeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Preco {
            get {
                return this.PrecoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrecoField, value) != true)) {
                    this.PrecoField = value;
                    this.RaisePropertyChanged("Preco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProdutoId {
            get {
                return this.ProdutoIdField;
            }
            set {
                if ((this.ProdutoIdField.Equals(value) != true)) {
                    this.ProdutoIdField = value;
                    this.RaisePropertyChanged("ProdutoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantidade {
            get {
                return this.QuantidadeField;
            }
            set {
                if ((this.QuantidadeField.Equals(value) != true)) {
                    this.QuantidadeField = value;
                    this.RaisePropertyChanged("Quantidade");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IGerenciamentoDeProdutoService")]
    public interface IGerenciamentoDeProdutoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGerenciamentoDeProdutoService/Create", ReplyAction="http://tempuri.org/IGerenciamentoDeProdutoService/CreateResponse")]
        void Create(Tp3_Azure.Client.ServiceReference1.Produto p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGerenciamentoDeProdutoService/Create", ReplyAction="http://tempuri.org/IGerenciamentoDeProdutoService/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(Tp3_Azure.Client.ServiceReference1.Produto p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGerenciamentoDeProdutoService/Get", ReplyAction="http://tempuri.org/IGerenciamentoDeProdutoService/GetResponse")]
        Tp3_Azure.Client.ServiceReference1.Produto Get(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGerenciamentoDeProdutoService/Get", ReplyAction="http://tempuri.org/IGerenciamentoDeProdutoService/GetResponse")]
        System.Threading.Tasks.Task<Tp3_Azure.Client.ServiceReference1.Produto> GetAsync(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGerenciamentoDeProdutoService/GetAll", ReplyAction="http://tempuri.org/IGerenciamentoDeProdutoService/GetAllResponse")]
        Tp3_Azure.Client.ServiceReference1.Produto[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGerenciamentoDeProdutoService/GetAll", ReplyAction="http://tempuri.org/IGerenciamentoDeProdutoService/GetAllResponse")]
        System.Threading.Tasks.Task<Tp3_Azure.Client.ServiceReference1.Produto[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGerenciamentoDeProdutoService/Edit", ReplyAction="http://tempuri.org/IGerenciamentoDeProdutoService/EditResponse")]
        void Edit(System.Guid produtoId, Tp3_Azure.Client.ServiceReference1.Produto p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGerenciamentoDeProdutoService/Edit", ReplyAction="http://tempuri.org/IGerenciamentoDeProdutoService/EditResponse")]
        System.Threading.Tasks.Task EditAsync(System.Guid produtoId, Tp3_Azure.Client.ServiceReference1.Produto p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGerenciamentoDeProdutoService/Delete", ReplyAction="http://tempuri.org/IGerenciamentoDeProdutoService/DeleteResponse")]
        void Delete(System.Guid produtoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGerenciamentoDeProdutoService/Delete", ReplyAction="http://tempuri.org/IGerenciamentoDeProdutoService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(System.Guid produtoId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGerenciamentoDeProdutoServiceChannel : Tp3_Azure.Client.ServiceReference1.IGerenciamentoDeProdutoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GerenciamentoDeProdutoServiceClient : System.ServiceModel.ClientBase<Tp3_Azure.Client.ServiceReference1.IGerenciamentoDeProdutoService>, Tp3_Azure.Client.ServiceReference1.IGerenciamentoDeProdutoService {
        
        public GerenciamentoDeProdutoServiceClient() {
        }
        
        public GerenciamentoDeProdutoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GerenciamentoDeProdutoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GerenciamentoDeProdutoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GerenciamentoDeProdutoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Create(Tp3_Azure.Client.ServiceReference1.Produto p) {
            base.Channel.Create(p);
        }
        
        public System.Threading.Tasks.Task CreateAsync(Tp3_Azure.Client.ServiceReference1.Produto p) {
            return base.Channel.CreateAsync(p);
        }
        
        public Tp3_Azure.Client.ServiceReference1.Produto Get(string nome) {
            return base.Channel.Get(nome);
        }
        
        public System.Threading.Tasks.Task<Tp3_Azure.Client.ServiceReference1.Produto> GetAsync(string nome) {
            return base.Channel.GetAsync(nome);
        }
        
        public Tp3_Azure.Client.ServiceReference1.Produto[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Tp3_Azure.Client.ServiceReference1.Produto[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public void Edit(System.Guid produtoId, Tp3_Azure.Client.ServiceReference1.Produto p) {
            base.Channel.Edit(produtoId, p);
        }
        
        public System.Threading.Tasks.Task EditAsync(System.Guid produtoId, Tp3_Azure.Client.ServiceReference1.Produto p) {
            return base.Channel.EditAsync(produtoId, p);
        }
        
        public void Delete(System.Guid produtoId) {
            base.Channel.Delete(produtoId);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(System.Guid produtoId) {
            return base.Channel.DeleteAsync(produtoId);
        }
    }
}
